### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by cfnptr** [InjectorGames/TetrisGame#1]
# Task list

## Common
- [x] Create repository
- [x] Add all team contributors

## Programming
- [x] Create 2D rendering engine (@QuantumBranch)
- [x] Find best rendering solution (@QuantumBranch)
- [ ] Do not load texture for each block, use shared instance array.
- [ ] Create main game classes.
- [ ] Make UI shader with borders
- [ ] Do not use MVP matrix, because only 2D.

## Painting
- [x] Invite at least one artist :D
- [ ] Winter blocks theme (@plesen-san)
- [x] Minimalistic blocks theme (@Animeska34)

**Comment by cfnptr** [comment]
Feel free to edit or add tasks.
